FROM ubuntu:18.04

# This is the latest PSW version we are currently supporting. This may change in the future and you may require to update it
# In that case, refer: https://01.org/intel-software-guard-extensions/downloads
ARG PSW_VERSION=2.11

# Use the APT preference file to pin sgx packages to specific versions
# Reference https://manpages.debian.org/buster/apt/apt_preferences.5.en.html
# Download the pref file from https://download.01.org/intel-sgx/sgx_repo/ubuntu/apt_preference_files/
# Assuming file name to follow *sgx_<PSW_VERSION>_bionic_custom_version.cfg convention
RUN apt-get update && apt-get install -y \
    wget \
    gnupg
RUN ["/bin/bash", "-c", "wget -r -l1 --no-parent -nd -A *sgx_$(echo ${PSW_VERSION//./_})_bionic_custom_version.cfg https://download.01.org/intel-sgx/sgx_repo/ubuntu/apt_preference_files/"]
RUN ["/bin/bash", "-c", "mv *sgx_$(echo ${PSW_VERSION//./_})_bionic_custom_version.cfg /etc/apt/preferences.d/intel-sgx.pref"]


# Add the repository to sources, and add the key to the list of
# trusted keys used by the apt to authenticate packages
RUN echo "deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main" | tee /etc/apt/sources.list.d/intel-sgx.list \
    && wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add -
# Add Microsoft repo for az-dcap-client
RUN echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" | tee /etc/apt/sources.list.d/msprod.list \
    && wget -qO - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -


RUN apt-get update && apt-get install -y \
    clang-7 \
    libssl-dev \
    gdb \
    libprotobuf10 \
    libsgx-dcap-ql \
    libsgx-quote-ex \
    az-dcap-client \
    git

# Install openenclave from source
RUN git clone https://github.com/salsal97/openenclave.git \
    && cd openenclave \
    && git fetch && git checkout sagoel_attestation \
    && git submodule update --recursive --init \
    && scripts/ansible/install-ansible.sh \
    && ansible-playbook scripts/ansible/oe-contributors-acc-setup-no-driver.yml \
    && mkdir build && cd build \
    && cmake -G "Unix Makefiles" .. \
    && make \
    && make install

# # Go to attestation sample
WORKDIR /openenclave/samples/attestation

## Source openenclaverc, Set up environment variables
RUN . /opt/openenclave/share/openenclave/openenclaverc \
    && export CC=gcc && export CXX=g++ && export PKG_CONFIG_PATH=/opt/openenclave/share/pkgconfig/ \
    && make build


# ## The following sets the flag for out of proc attestation mode. Alternatively you can set this flag on the deployment files
ENV SGX_AESM_ADDR=1


# ## Set the command to run the getting-report application, to validate that a report can be gotten
# CMD make runsgxlocal