// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted getting_report header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the getting_report.edl file.
#include "getting_report_t.h"

// This is the function that the host calls. It tries
// to generate a report & fails if it cannot
void enclave_getting_report()
{

    static uint8_t* report;
    size_t report_size = 0;

    // Generate reports.
    oe_result_t get_report_result = oe_get_report(
        OE_REPORT_FLAGS_REMOTE_ATTESTATION,
        NULL,
        0,
        NULL,
        0,
        &report,
        &report_size);

    if (get_report_result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_get_report failed: result=%u (%s)\n",
            get_report_result,
            oe_result_str(get_report_result));
    }
    printf(
        "oe_get_report passed: result=%u (%s)\n",
        get_report_result,
        oe_result_str(get_report_result));

    // Verify the report.
    oe_result_t verify_report_result = oe_verify_report(report, report_size, NULL);
    if (verify_report_result != OE_OK) 
    {
        fprintf(
            stderr,
            "oe_verify_report failed: result=%u (%s)\n",
            verify_report_result,
            oe_result_str(verify_report_result));
    }
    printf(
        "oe_get_verify_report passed: result=%u (%s)\n",
        verify_report_result,
        oe_result_str(verify_report_result));
    
    oe_free_report(report);
}
